# (공부) Julia – Vector

신록예찬  
2023-10-26

# 1. 느낌

`-` Python의 리스트와 비슷하기도 하고, numpy array와 비슷하기도 함

# 2. 선언과 자료형

`-` 예시1

In [3]:
a = [1,2,3]
a

3-element Vector{Int64}:
 1
 2
 3

In [4]:
typeof(a)

Vector{Int64} (alias for Array{Int64, 1} )

`-` 예시2

In [5]:
a = [1,2,'a',"abc"] 
a

4-element Vector{Any}:
 1
 2
  'a': ASCII/Unicode U+0061 (category Ll: Letter, lowercase)
  "abc"

In [6]:
typeof(a)

Vector{Any} (alias for Array{Any, 1} )

`-` 예시3 – col-vector처럼 선언가능

In [7]:
a= [ 1
     2
     3 ] 

3-element Vector{Int64}:
 1
 2
 3

`-` 예시4 – 비어있는 벡터 선언

In [8]:
a = []

Any[]

# 3. 특수한 벡터 선언

`-` 예시1: ones, zeros

In [14]:
ones(3)

3-element Vector{Float64}:
 1.0
 1.0
 1.0

In [16]:
zeros(3)

3-element Vector{Float64}:
 0.0
 0.0
 0.0

`-` 예시2: fill

In [18]:
fill(1.0,3)

3-element Vector{Float64}:
 1.0
 1.0
 1.0

`-` 예시3

In [35]:
Array(1:3)
#Array(range(1,3))

3-element Vector{Int64}:
 1
 2
 3

In [37]:
collect(1:3)
#collect(range(1,3))

3-element Vector{Int64}:
 1
 2
 3

`-` 예시4

In [28]:
Array(range(1,10,length=3))

3-element Vector{Float64}:
  1.0
  5.5
 10.0

In [29]:
collect(range(1,10,length=3))

3-element Vector{Float64}:
  1.0
  5.5
 10.0

# 4. 연산

## A. 더하기

`-` 예시1 – 길이가 같은 벡터의 합

In [104]:
a = [1,2] 
b = [-1,-2]
a + b

2-element Vector{Int64}:
 0
 0

In [105]:
# 사실아래도 가능
a .+ b

2-element Vector{Int64}:
 0
 0

`-` 예시2 – 벡터+스칼라 (실패)

In [65]:
a = [1,2]
a + 1 # 브로드캐스팅 실패

`-` 예시3 – 벡터+스칼라 (성공)

In [66]:
a = [1,2]
a .+ 1 

2-element Vector{Int64}:
 2
 3

## B. 곱셉

`-` 예시1 – 벡터\*스칼라 (성공)

In [147]:
a = [1,2]
a*2

2-element Vector{Int64}:
 2
 4

In [148]:
# 사실 아래도 가능
a .* 2

2-element Vector{Int64}:
 2
 4

In [68]:
# 사실 아래도 가능
2a

2-element Vector{Int64}:
 2
 4

`-` 예시2 – 하다마르곱

In [53]:
a = [1,2]
b = [2,3] 
a .* b 

2-element Vector{Int64}:
 2
 6

`-` 예시3 – 예시2를 응용

In [69]:
a = [1,'a']
b = [3,'b']
a .* b

2-element Vector{Any}:
 3
  "ab"

## C. 제곱연산

`-` 예시1

In [149]:
a = [1,2]
a .^ 2

2-element Vector{Int64}:
 1
 4

`-` 예시2

In [150]:
a = ["a", "bb"] 
a .^ 2 

2-element Vector{String}:
 "aa"
 "bbbb"

## D. 내적

`-` 예시

In [161]:
using LinearAlgebra

In [164]:
[1,2,3] ⋅ [1,2,3]

14

In [165]:
dot([1,2,3],[1,2,3])

14

In [166]:
[1,2,3]' * [1,2,3]

14

# 5. 차원, 길이, 차원변경

`-` 예시1

In [108]:
a = 1:4
a

1:4

In [109]:
ndims(a)

1

In [110]:
length(a)

4

`-` 예시2

In [111]:
a = 1:4

1:4

In [113]:
a = reshape(a,(2,2))
a

2×2 reshape(::UnitRange{Int64}, 2, 2) with eltype Int64:
 1  3
 2  4

In [114]:
ndims(a)

2

In [116]:
length(a)

4

# 6. 조건에 맞는 원소 출력

`-` 예시1

In [152]:
a = collect(10:5:30)
a

5-element Vector{Int64}:
 10
 15
 20
 25
 30

In [153]:
a[a .< 20]

2-element Vector{Int64}:
 10
 15

In [155]:
@. a[a < 20] # 이게 편할지도

2-element Vector{Int64}:
 10
 15

`-` 예시2

In [159]:
a = [1,2,3,4,5]
b = [5,4,3,2,1] 
@. a[a < b]

2-element Vector{Int64}:
 1
 2

# 7. 원소의 추가

## A. `append!`

`-` 예시

In [167]:
a = [1,2,3]
b = [4] 
append!(a,b)

4-element Vector{Int64}:
 1
 2
 3
 4

In [171]:
a,b

([1, 2, 3, 4], [4])

> `append!`는 numpy에서 concat 느낌

## B. `push!`

`-` 예시

In [174]:
a = [1,2,3]
push!(a,4)

4-element Vector{Int64}:
 1
 2
 3
 4

> `push!`는 list에서 append 느낌

# 8. 결합

## A. `cat`

> np.concat, np.stack 등이 합쳐진 형태

`-` 예시1

In [193]:
a = [1,2,3]
b = [4] 

1-element Vector{Int64}:
 4

In [194]:
cat(a,b,dims=1) # np.concat 과 비슷

4-element Vector{Int64}:
 1
 2
 3
 4

`-` 예시2

In [179]:
a = [1,2,3]
b = -a

3-element Vector{Int64}:
 -1
 -2
 -3

In [181]:
cat(a,b,dims=2) 

3×2 Matrix{Int64}:
 1  -1
 2  -2
 3  -3

In [182]:
cat(a,b,dims=1)

6-element Vector{Int64}:
  1
  2
  3
 -1
 -2
 -3

`-` 예시3

In [189]:
a = [1 2 3
     3 4 5]
b = -a

2×3 Matrix{Int64}:
 -1  -2  -3
 -3  -4  -5

In [190]:
cat(a,b,dims=1)

4×3 Matrix{Int64}:
  1   2   3
  3   4   5
 -1  -2  -3
 -3  -4  -5

In [191]:
cat(a,b,dims=2)

2×6 Matrix{Int64}:
 1  2  3  -1  -2  -3
 3  4  5  -3  -4  -5

In [192]:
cat(a,b,dims=3)

2×3×2 Array{Int64, 3}:
[:, :, 1] =
 1  2  3
 3  4  5

[:, :, 2] =
 -1  -2  -3
 -3  -4  -5

`-` 예시4 – 아래도 가능

In [200]:
a = [1,2,3]
b = 2 
cat(a,b,dims=1)

4-element Vector{Int64}:
 1
 2
 3
 2

`-` 예시5 – 아래도 가능

In [201]:
a = reshape(1:4, (2,2))
b = [3,4]
a,b

([1 3; 2 4], [3, 4])

In [204]:
cat(a,b,dims=2)

2×3 Matrix{Int64}:
 1  3  3
 2  4  4

## B. `[]`를 이용한 결합

`-` 예시1

In [206]:
a = [1,2,3]
b = -a
a,b

([1, 2, 3], [-1, -2, -3])

In [207]:
[a b]

3×2 Matrix{Int64}:
 1  -1
 2  -2
 3  -3

In [208]:
[a
 b]

6-element Vector{Int64}:
  1
  2
  3
 -1
 -2
 -3

`-` 예시2

In [218]:
a = [1,2,3] 
b = 4

4

In [220]:
[a 
 b]

4-element Vector{Int64}:
 1
 2
 3
 4

`-` 예시3

In [229]:
a = [1 2; 3 4]
b = [0,0] 

2-element Vector{Int64}:
 0
 0

In [230]:
[a b]

2×3 Matrix{Int64}:
 1  2  0
 3  4  0